
title: Kunyu's Space
description: "A brief introduction of Kunyu Wang's education and research experience."
url: "https://wangkunyu.github.io/"
author: Kunyu Wang


author-image: /img/user.png

baseurl: ""  # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown


#color scheme
sidebar-color: '#000'       #those apostrophes are important
accent-color: #8B008B'     #those apostrophes are important


#social
facebook: https://www.facebook.com/
twitter: https://twitter.com/
twitter-handle: ''     #for twitter button on author section #those apostrophes are important
github: https://github.com/
youtube: https://www.youtube.com/channel/
email: wangkunyu95@qq.com
feedburner-subscribe: https://feedburner.google.com/fb/a/mailverify?uri=webjedablog&amp;loc=en_US

#Other
analytics: UA-71358787-1
disqus-shortname: webjeda-sample    #Disqus comments
google-custom-search-cx: '017575011755499056211:vwrwldvgq6s'        #Create Custom Search Engine(CSE) with google and find this ID in the code they provide.


# Get this from https://getsimpleform.com to make your contact form work as expected.
simpleform-api-token:


destination: ./_site
permalink: /:title/
paginate: 6
paginate_path: /page:num/

sass:
    style: compressed
    
gems: [jekyll-paginate]


